version: "2"
services:
    web:
        image: abiosoft/caddy:php
        ports:
            - "10119:2015"
        volumes:
            - ./server:/srv/
            - ./server/git:/srv/.git/
            - ../Caddyfile:/etc/Caddyfile
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.119.0/24
