version: "2"
services:
    web:
        build: ./flask
        ports:
            - "10106:80"
        volumes:
            - ./flask/app:/app
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.106.0/24
