version: "2"
services:
    web:
        image: php:7-apache
        ports:
            - "10109:80"
        volumes:
            - ./server:/var/www/html/
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.109.0/24
