version: "2"
services:
    web:
        build: ./
        ports:
            - "10111:10023"
        volumes:
            - ./server:/srv/
            - ./flag:/flag
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.28.111.0/24
