version: "2"
services:
    web:
        image: abiosoft/caddy:php
        ports:
            - "10009:2015"
        volumes:
            - ./server:/srv/
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.28.9.0/24
