version: "2"
services:
    web:
        image: php:7-apache
        ports:
            - "10110:80"
        volumes:
            - ./server:/var/www/html/
            - ./flag:/flag/
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.110.0/24
